### ISSUE TITLE
Are you OK?

### ISSUE THREAD

**Issue by yiboin** [willard-yuan/CNN-for-Face-Image-Retrieval#1]
You know , I mean the QT project... 
Best Regards

**Comment by willard-yuan** [comment]
Hi yiboin,
Thank you for your interest for the QT project. I have finished the QT project for face image retrieval, and you can access to the QT project by the hyperlinks: [SeetaFaceLib](https://github.com/willard-yuan/SeetaFaceLib). If you have some problems when installing and running the project, feel free to ask me.
