### ISSUE TITLE
Isn't the 36th layer of 2622 dimension?

### ISSUE THREAD

**Issue by surlogics** [willard-yuan/CNN-for-Face-Image-Retrieval#2]
Hi, I've noticed your extractCNN.m picks up FC activations from the 36th layer. As far as I see, 36th layer is FC8 and it is of 2622 dimensions. Shouldn't you pick up FC activations from 34th layer (FC7). Or am I see it wrong? Thanks for your help.

**Comment by willard-yuan** [comment]
@surlogics The MatConvNet and the model may be changed a little. I tested it about a year ago. And  the feature dimension is 4096D I extracted. So it's good to choose the layer whose dimension is 4096d.

**Comment by surlogics** [comment]
OK! Thanks for your help!
